name: Compatibility Build

on:
  workflow_dispatch:
  schedule:
    - cron: '5 6 * * *'

jobs:
  integration:
    strategy:
      matrix:
        version:
        - '3.1.12'
        - '3.1.13-SNAPSHOT'
        - '3.2.6'
        - '3.2.7-SNAPSHOT'
        - '3.3.1-SNAPSHOT'
    name: Build against Boot ${{ matrix.version }}
    runs-on: ubuntu-latest

    steps:

    - name: Check out sources
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'

    - name: Build with Maven
      env:
        COMMERCIAL_USERNAME: ${{ secrets.COMMERCIAL_ARTIFACTORY_RO_USERNAME }}
        COMMERCIAL_PASSWORD: ${{ secrets.COMMERCIAL_ARTIFACTORY_RO_PASSWORD }}
        DEVELOCITY_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
      run: |
        cd spring-modulith-examples
        ../mvnw -B versions:update-parent -s ../settings.xml -Pwith-preview-repos,with-commercial-repos -DskipResolution=true -DparentVersion=${{ matrix.version }}
        ../mvnw -B clean verify -s ../settings.xml -Pwith-preview-repos,with-commercial-repos -Dspring-boot.version=${{ matrix.version }}
